Repository JodaOrg/joda-beans, pull requests merged in 2022-08, with the labels that each got.

#235 Referencing bin reader: handle classes referenced in custom deserializers
  src/main/java/org/joda/beans/ser/bin/JodaBeanReferencingBinReader.java
  src/test/java/org/joda/beans/sample/ImmKeyHolder.java
  src/test/java/org/joda/beans/sample/ImmKeyHolderDeserializer.java
  src/test/java/org/joda/beans/ser/SerTestHelper.java
  src/test/java/org/joda/beans/ser/bin/TestSerializeReferencingBin.java
  src/test/resources/META-INF/org/joda/beans/JodaBeans.ini
Labels: Bug, Fixed

#236 Update dependencies, add dependabot
  .github/dependabot.yml
  .github/workflows/build.yml
  pom.xml
  src/main/java/org/joda/beans/MetaProvider.java
Labels: Fixed, dependencies

#237 Switch to AssertJ
  pom.xml
  src/test/java/org/joda/beans/TestAddress.java
  src/test/java/org/joda/beans/TestArray.java
  src/test/java/org/joda/beans/TestBasicBean.java
  src/test/java/org/joda/beans/TestBeanCodeGenException.java
  src/test/java/org/joda/beans/TestBeanIterator.java
  src/test/java/org/joda/beans/TestClone.java
  src/test/java/org/joda/beans/TestCompanyAddress.java
  src/test/java/org/joda/beans/TestFinalFieldBean.java
  src/test/java/org/joda/beans/TestFlexiBean.java
  src/test/java/org/joda/beans/TestImmutable.java
  src/test/java/org/joda/beans/TestJodaBeanUtils.java
  src/test/java/org/joda/beans/TestLight.java
  src/test/java/org/joda/beans/TestMapBean.java
  src/test/java/org/joda/beans/TestMetaBean.java
  src/test/java/org/joda/beans/TestMetaBeans.java
  src/test/java/org/joda/beans/TestMinimal.java
  src/test/java/org/joda/beans/TestMutableDerived.java
  src/test/java/org/joda/beans/TestMutableListBeans.java
  src/test/java/org/joda/beans/TestOptionalBean.java
  src/test/java/org/joda/beans/TestPair.java
  src/test/java/org/joda/beans/TestPerson.java
  src/test/java/org/joda/beans/TestPropertyStyle.java
  src/test/java/org/joda/beans/TestReflective.java
  src/test/java/org/joda/beans/TestResult.java
  src/test/java/org/joda/beans/TestSubBean.java
  src/test/java/org/joda/beans/TestValidateBean.java
  src/test/java/org/joda/beans/sample/TestRWOnlyBean.java
  src/test/java/org/joda/beans/ser/TestSerDeserializerProvider.java
  src/test/java/org/joda/beans/ser/TestSerTypeMapper.java
  src/test/java/org/joda/beans/ser/TestSerializeSmartReader.java
  src/test/java/org/joda/beans/ser/bin/TestSerializeReferencingBin.java
  src/test/java/org/joda/beans/ser/bin/TestSerializeStandardBin.java
  src/test/java/org/joda/beans/ser/json/TestJsonInput.java
  src/test/java/org/joda/beans/ser/json/TestJsonOutput.java
  src/test/java/org/joda/beans/ser/json/TestSerializeJson.java
  src/test/java/org/joda/beans/ser/json/TestSerializeJsonSimple.java
  src/test/java/org/joda/beans/ser/map/TestSerializeSimpleMap.java
  src/test/java/org/joda/beans/ser/xml/TestDeserializer.java
  src/test/java/org/joda/beans/ser/xml/TestSerializeXml.java
  src/test/java/org/joda/beans/test/TestBeanAssert.java
  src/test/java/org/joda/beans/test/TestCoverage.java
Labels: Fixed, Task

#238 Switch to JUnit 5
  pom.xml
  src/test/java/org/joda/beans/TestAddress.java
  src/test/java/org/joda/beans/TestArray.java
  src/test/java/org/joda/beans/TestBasicBean.java
  src/test/java/org/joda/beans/TestBeanCodeGenException.java
  src/test/java/org/joda/beans/TestBeanIterator.java
  src/test/java/org/joda/beans/TestClone.java
  src/test/java/org/joda/beans/TestCompanyAddress.java
  src/test/java/org/joda/beans/TestFinalFieldBean.java
  src/test/java/org/joda/beans/TestFlexiBean.java
  src/test/java/org/joda/beans/TestImmutable.java
  src/test/java/org/joda/beans/TestJodaBeanUtils.java
  src/test/java/org/joda/beans/TestLight.java
  src/test/java/org/joda/beans/TestMapBean.java
  src/test/java/org/joda/beans/TestMetaBean.java
  src/test/java/org/joda/beans/TestMetaBeans.java
  src/test/java/org/joda/beans/TestMetaInvoke.java
  src/test/java/org/joda/beans/TestMinimal.java
  src/test/java/org/joda/beans/TestMutableDerived.java
  src/test/java/org/joda/beans/TestMutableListBeans.java
  src/test/java/org/joda/beans/TestOptionalBean.java
  src/test/java/org/joda/beans/TestPair.java
  src/test/java/org/joda/beans/TestPerson.java
  src/test/java/org/joda/beans/TestPropertyStyle.java
  src/test/java/org/joda/beans/TestReflective.java
  src/test/java/org/joda/beans/TestResult.java
  src/test/java/org/joda/beans/TestSubBean.java
  src/test/java/org/joda/beans/TestValidateBean.java
  src/test/java/org/joda/beans/impl/flexi/TestFlexiBean.java
  src/test/java/org/joda/beans/sample/ImmDefault.java
  src/test/java/org/joda/beans/sample/ImmDoubleArray.java
  src/test/java/org/joda/beans/sample/ImmKeyHolderDeserializer.java
  src/test/java/org/joda/beans/sample/TestRWOnlyBean.java
  src/test/java/org/joda/beans/ser/TestSerDeserializerProvider.java
  src/test/java/org/joda/beans/ser/TestSerTypeMapper.java
  src/test/java/org/joda/beans/ser/TestSerializeSmartReader.java
  src/test/java/org/joda/beans/ser/bin/TestSerializeReferencingBin.java
  src/test/java/org/joda/beans/ser/bin/TestSerializeStandardBin.java
  src/test/java/org/joda/beans/ser/json/TestJsonInput.java
  src/test/java/org/joda/beans/ser/json/TestJsonOutput.java
  src/test/java/org/joda/beans/ser/json/TestSerializeJson.java
  src/test/java/org/joda/beans/ser/json/TestSerializeJsonSimple.java
  src/test/java/org/joda/beans/ser/map/TestSerializeSimpleMap.java
  src/test/java/org/joda/beans/ser/xml/TestDeserializer.java
  src/test/java/org/joda/beans/ser/xml/TestSerializeXml.java
  src/test/java/org/joda/beans/test/TestBeanAssert.java
  src/test/java/org/joda/beans/test/TestCoverage.java
Labels: Fixed, Task
